# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text2',
            field=models.CharField(default='Questao vazia', max_length=500),
        ),
    ]
