# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_question_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text3',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
