# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170606_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
